spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/lock_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:change_me}
spring.jpa.hibernate.ddl-auto=update

#dev/prod
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
api.security.token.secret=${JWT_SECRET:change_me}
app.crypto.key=${APP_CRYPTO_KEY:change_me}

#Conexao com o H2
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
